[workspace]
channels = ["conda-forge"]
name = "BINF-5507-Materials"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
python = ">=3.13.3,<3.14"
pip = ">=25.1.1,<26"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.6.1,<2"
numpy = ">=2.2.6,<3"
ipykernel = ">=6.29.5,<7"
umap-learn = ">=0.5.7,<0.6"
pydicom = ">=3.0.1,<4"
nibabel = ">=5.3.2,<6"
ipywidgets = ">=8.1.7,<9"
scikit-survival = ">=0.24.1,<0.25"
lifelines = ">=0.30.0,<0.31"

[feature.new.dependencies]
python = "3.7.*"
ipykernel = "*"

[feature.new.pypi-dependencies]
pyradiomics = "<3.0"

[environments]
new = {features=["new"], no-default-feature=true}

[feature.new]
platforms=["osx-64"]
